name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
    - name: Enable Firewall Rule for RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Enable RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
    - name: Set RDP Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
    - name: Install OpenSSH (if not installed)
      run: Add-WindowsCapability -Online -Name OpenSSH.Client
    - name: Create Serveo Tunnel
      run: ssh -o StrictHostKeyChecking=no -R 3389:localhost:3389 serveo.net
